const {JSDOM}=require('jsdom');const fs=require('node:fs');const vm=require('node:vm');const assert=require('node:assert/strict');
(async()=>{
 const html=fs.readFileSync('index.html','utf8');const dom=new JSDOM(html,{url:'https://planner.test/',runScripts:'outside-only',pretendToBeVisual:true});const w=dom.window,ctx=dom.getInternalVMContext();
 Object.assign(w,{structuredClone,TextEncoder,TextDecoder,AbortController,Response,Request,confirm:()=>true,alert(){},fetch:async()=>new Response(JSON.stringify({requiresAccess:true,protocolVersion:2,apiVersion:'2026.10.06.29'}))});
 w.HTMLElement.prototype.scrollIntoView=function(){};
 for(const script of w.document.querySelectorAll('script'))if(!script.src)vm.runInContext(script.textContent,ctx);
 vm.runInContext(fs.readFileSync('sync-core.js','utf8'),ctx);vm.runInContext(fs.readFileSync('google-calendar.js','utf8'),ctx);
 vm.runInContext("tasks=[{id:123,title:'Test DOM',date:'2026-10-06',time:'13:00',endTime:'13:15',notes:'',location:''}];saveTasks();renderAll();openEventActions(tasks[0]);",ctx);
 assert.equal(w.document.getElementById('actionTitle').textContent,'Test DOM');
 await vm.runInContext("processEventVoiceResult({transcription:'do 15:00',item:{...voiceEventSnapshot(tasks[0]),endTime:'15:00',changedFields:['endTime']}},123)",ctx);
 assert.equal(vm.runInContext('tasks[0].endTime',ctx),'15:00');assert.equal(vm.runInContext('tasks[0].title',ctx),'Test DOM');
 await vm.runInContext("processEventVoiceResult({transcription:'całodniowe',item:{...voiceEventSnapshot(tasks[0]),startTime:'',endTime:'',changedFields:['startTime','endTime']}},123)",ctx);
 assert.equal(vm.runInContext('tasks[0].time',ctx),'');assert.equal(vm.runInContext('tasks[0].endDate',ctx),'2026-10-07');
 vm.runInContext(`saveGoogleDeleteQueue([{googleEventId:'fake',state:'conflict',localSnapshot:{title:'<img src=x onerror="window.xssExecuted=true">'}}]);renderGoogleDeleteConflicts();`,ctx);
 assert.equal(w.document.querySelectorAll('#googleDeleteConflicts img').length,0);assert.match(w.document.getElementById('googleDeleteConflicts').textContent,/<img/);
 const record=JSON.parse(w.localStorage.getItem('moj-planer-data-v1'));assert.equal(record.data.tasks[0].endDate,'2026-10-07');
 vm.runInContext("addIdea({type:'idea',text:'Lista zakupów',listAction:'replace',items:['jajka','chleb']});applyVoiceUiAction({}, {type:'find_entry',query:'lista zakupów'});",ctx);
 assert.equal(w.document.getElementById('entryResultsModal').classList.contains('hidden'),false);assert.equal(w.document.querySelectorAll('#entryResults .entry-result').length,1);w.document.querySelector('#entryResults .entry-result').click();
 assert.equal(w.document.getElementById('ideaModal').classList.contains('hidden'),false);assert.equal(w.document.querySelectorAll('#ideaText .shopping-list li').length,2);
 vm.runInContext("for(let i=0;i<12;i++)ideas.push({id:'s'+i,type:'idea',entryType:'task',text:'Spotkanie z Wojtkiem',title:'Spotkanie z Wojtkiem',createdAt:new Date().toISOString(),done:false,history:[]});tasks.push({id:'match',title:'Spotkanie z Wojtkiem',date:'2026-10-09',time:'10:00',createdAt:new Date().toISOString()},{id:'other-date',title:'Spotkanie z Wojtkiem',date:'2026-10-10',time:'10:00',createdAt:new Date().toISOString()});applyVoiceUiAction({}, {type:'find_entry',query:'spotkanie z Wojtkiem'});",ctx);
 assert.equal(w.document.querySelectorAll('#entryResults .entry-result').length,14,'all matching entries should remain available in the scrollable results list');
 const resultsStyle=w.getComputedStyle(w.document.querySelector('#entryResults'));assert.ok(parseFloat(resultsStyle.maxHeight)<w.innerHeight,'search results should have a bounded height');assert.equal(resultsStyle.overflowY,'auto','search results should be scrollable');
 vm.runInContext("applyVoiceUiAction({}, {type:'find_entry',query:'spotkanie z Wojtkiem',date:'2026-10-09'});",ctx);assert.equal(w.document.querySelectorAll('#entryResults .entry-result').length,1,'date and person filters should reduce broad title matches');
 vm.runInContext("applyVoiceUiAction({}, {type:'open_create_event',query:'spotkanie z Wojtkiem'});",ctx);assert.equal(vm.runInContext('voiceDialogues.main.dialogueState.draft.date',ctx),'2026-10-09','a follow-up create command should retain the searched date');assert.match(w.document.getElementById('mainClarification').textContent,/O której godzinie/,'the assistant should ask for missing event details');
 vm.runInContext("applyVoiceUiAction({}, {type:'find_entry',query:'spotkanie o wynajmie mieszkania',date:'2026-10-09'});",ctx);
 assert.equal(w.document.getElementById('entryResultsModal').classList.contains('hidden'),true);assert.equal(vm.runInContext('voiceDialogues.main.dialogueState.draft.title',ctx),'spotkanie o wynajmie mieszkania');assert.equal(vm.runInContext('voiceDialogues.main.dialogueState.draft.date',ctx),'2026-10-09');assert.match(w.document.getElementById('mainClarification').textContent,/O której godzinie/,'a no-hit search should begin a guided event draft');
 assert.equal(vm.runInContext("plannerItemQuestion({type:'idea',text:'Lista zakupów',listAction:'replace',items:[]})",ctx),null,'an empty shopping list is a valid draft');
 vm.runInContext("addIdea({type:'idea',text:'Lista zakupów',listAction:'replace',items:[]});addIdea({type:'idea',entryType:'note',text:'Notatka na próbę'});ideasTypeMode='all';renderIdeas();",ctx);
 assert.equal(w.document.querySelectorAll('#ideasList .idea').length,15,'one combined view should contain ideas, tasks, shopping lists and notes');
 const ideaId=vm.runInContext("ideas.find(i=>i.list?.items.some(x=>x.text==='jajka'))?.id",ctx);await vm.runInContext(`processIdeaVoiceResult({transcription:'usuń chleb',item:{type:'idea',text:'Lista zakupów',action:'replace',addition:null,listAction:'remove',items:['chleb']}},${JSON.stringify(ideaId)})`,ctx);
 assert.equal(vm.runInContext(`JSON.stringify(ideas.find(i=>i.id===${JSON.stringify(ideaId)}).list.items.map(x=>x.text))`,ctx),'["jajka"]');assert.ok(vm.runInContext(`ideas.find(i=>i.id===${JSON.stringify(ideaId)}).history.length>=2`,ctx));
 vm.runInContext(`showEntryHistory(ideas.find(i=>i.id===${JSON.stringify(ideaId)}))`,ctx);assert.match(w.document.getElementById('historyList').textContent,/Usunięto: chleb/);
 console.log('DOM: event edits, shopping lists, cross-type search, history and conflict safety passed.');dom.window.close();
})().catch(e=>{console.error(e);process.exitCode=1});
